spring:
  datasource:
    url: jdbc:h2:tcp://localhost///media/test
    driver-class-name: org.h2.Driver
  service:
    hibernate:
      ddl-auto: none

liquibase:
  change-log: classpath:db/changelog/db.changelog-master.xml

hibernate:
  dialect: org.hibernate.dialect.H2Dialect
